services:
  - type: web
    name: streamlitflights
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Home.py --server.address 0.0.0.0 --server.port $PORT
